-- ##############################################################
-- ## MICROSERVICIO: GESTION USUARIO CLIENTE (IDENTIDAD)
-- ##############################################################

CREATE TABLE Rol (
    id_rol      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_rol  VARCHAR2(100) NOT NULL UNIQUE,
    CONSTRAINT pk_rol PRIMARY KEY (id_rol)
);

CREATE TABLE Usuario (
    id_usuario  VARCHAR2(255) NOT NULL,
    id_rol      NUMBER(10) NOT NULL,
    email       VARCHAR2(255) NOT NULL UNIQUE,
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario)
);

CREATE TABLE Cliente (
    id_cliente      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario      VARCHAR2(255) NOT NULL UNIQUE,
    nombre_cliente  VARCHAR2(255) NOT NULL,
    telefono_cliente VARCHAR2(20),
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente)
);

CREATE TABLE Trabajador (
    id_trabajador   NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_usuario      VARCHAR2(255) NOT NULL UNIQUE,
    nombre_trabajador VARCHAR2(255) NOT NULL,
    rut_trabajador  VARCHAR2(12) NOT NULL UNIQUE,
    CONSTRAINT pk_trabajador PRIMARY KEY (id_trabajador)
);

CREATE TABLE Ciudad (
    id_ciudad     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_ciudad VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad)
);

CREATE TABLE DireccionCliente (
    id_direccion    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_cliente      NUMBER(10) NOT NULL,
    id_ciudad       NUMBER(10) NOT NULL,
    direccion       VARCHAR2(500) NOT NULL,
    alias           VARCHAR2(100),
    CONSTRAINT pk_direccion_cliente PRIMARY KEY (id_direccion)
);

-- ##############################################################
-- ## MICROSERVICIO: GESTION CATALOGO (PRODUCTOS)
-- ##############################################################

CREATE TABLE CategoriaProducto (
    id_categoria    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_categoria VARCHAR2(255) NOT NULL UNIQUE,
    descripcion     VARCHAR2(1000),
    CONSTRAINT pk_categoria_producto PRIMARY KEY (id_categoria)
);

CREATE TABLE Producto (
    id_producto     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_categoria    NUMBER(10) NOT NULL,
    nombre_producto VARCHAR2(255) NOT NULL,
    descripcion     VARCHAR2(1000),
    precio_base     NUMBER(10, 2) NOT NULL,
    imagen_url      VARCHAR2(1000),
    disponible      NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_producto PRIMARY KEY (id_producto),
    CONSTRAINT chk_producto_disponible CHECK (disponible IN (0, 1)),
    CONSTRAINT chk_producto_precio CHECK (precio_base > 0)
);

-- ##############################################################
-- ## MICROSERVICIO: GESTION PEDIDO (ORDENES)
-- ##############################################################

CREATE TABLE EstadoPedido (
    id_estado_pedido    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_estado       VARCHAR2(100) NOT NULL UNIQUE,
    CONSTRAINT pk_estado_pedido PRIMARY KEY (id_estado_pedido)
);

CREATE TABLE MetodoPago (
    id_metodo_pago  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_metodo   VARCHAR2(100) NOT NULL UNIQUE,
    CONSTRAINT pk_metodo_pago PRIMARY KEY (id_metodo_pago)
);

CREATE TABLE TipoEntrega (
    id_tipo_entrega     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_entrega      VARCHAR2(100) NOT NULL UNIQUE,
    CONSTRAINT pk_tipo_entrega PRIMARY KEY (id_tipo_entrega)
);

CREATE TABLE Pedido (
    id_pedido           NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_cliente          NUMBER(10) NOT NULL,
    id_estado_pedido    NUMBER(10) NOT NULL,
    id_metodo_pago      NUMBER(10) NOT NULL,
    id_tipo_entrega     NUMBER(10) NOT NULL,
    id_direccion_cliente NUMBER(10),
    monto_subtotal      NUMBER(10, 2) NOT NULL,
    monto_envio         NUMBER(10, 2) DEFAULT 0 NOT NULL,
    monto_total         NUMBER(10, 2) NOT NULL,
    fecha_pedido        DATE DEFAULT SYSDATE NOT NULL,
    nota_cliente        VARCHAR2(255),
    CONSTRAINT pk_pedido PRIMARY KEY (id_pedido)
);

CREATE TABLE DetallePedido (
    id_detalle      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_pedido       NUMBER(10) NOT NULL,
    id_producto     NUMBER(10) NOT NULL,
    cantidad        NUMBER(10) NOT NULL,
    precio_unitario NUMBER(10, 2) NOT NULL,
    subtotal_linea  NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_detalle_pedido PRIMARY KEY (id_detalle)
);

-- ##############################################################
-- ## MICROSERVICIO: GESTION VENTA (REPORTES)
-- ##############################################################

CREATE TABLE Venta (
    id_venta            NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_pedido           NUMBER(10) NOT NULL UNIQUE,
    monto_total_venta   NUMBER(10, 2) NOT NULL,
    fecha_venta         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_venta PRIMARY KEY (id_venta)
);

CREATE TABLE Boleta (
    id_boleta       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_venta        NUMBER(10) NOT NULL UNIQUE,
    folio_sii       VARCHAR2(255),
    url_boleta      VARCHAR2(1000),
    iva             NUMBER(5,2) DEFAULT 19,
    CONSTRAINT pk_boleta PRIMARY KEY (id_boleta)
);

CREATE TABLE Devolucion (
    id_devolucion   NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_venta        NUMBER(10) NOT NULL,
    monto_devolucion NUMBER(10, 2) NOT NULL,
    motivo          VARCHAR2(1000),
    fecha_devolucion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_devolucion PRIMARY KEY (id_devolucion)
);

-- ##############################################################
-- ## MICROSERVICIO: GESTION CONTACTO
-- ##############################################################

CREATE TABLE MensajeContacto (
    id_mensaje      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_remitente VARCHAR2(255) NOT NULL,
    email_remitente VARCHAR2(255) NOT NULL,
    asunto          VARCHAR2(255),
    mensaje         VARCHAR2(4000) NOT NULL,
    fecha_recibido  DATE DEFAULT SYSDATE NOT NULL,
    leido           NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_mensaje_contacto PRIMARY KEY (id_mensaje),
    CONSTRAINT chk_mensaje_leido CHECK (leido IN (0, 1))
);



CREATE TABLE PAGO (
    id_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado_pago VARCHAR2(50),
    fecha_pago TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_pago_mpos VARCHAR2(100),
    id_pedido NUMBER NOT NULL,
    id_preferencia_mpos VARCHAR2(200),
    metodo_pago VARCHAR2(50),
    monto_pago NUMBER(10,2),
    respuesta_mercado_pago CLOB,
    CONSTRAINT fk_pago_pedido FOREIGN KEY (id_pedido) REFERENCES PEDIDO(id_pedido)
);

-- ##############################################################
-- ## FOREIGN KEYS (RESTRICCIONES DE INTEGRIDAD)
-- ##############################################################

ALTER TABLE BOLETA MODIFY IVA NUMBER(10,2);
ALTER TABLE BOLETA MODIFY TOTALCONIVA NUMBER(12,2);
ALTER TABLE Usuario ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES Rol(id_rol);
ALTER TABLE Cliente ADD CONSTRAINT fk_cliente_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario);
ALTER TABLE Trabajador ADD CONSTRAINT fk_trabajador_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario);
ALTER TABLE DireccionCliente ADD CONSTRAINT fk_direccion_cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente);
ALTER TABLE DireccionCliente ADD CONSTRAINT fk_direccion_ciudad FOREIGN KEY (id_ciudad) REFERENCES Ciudad(id_ciudad);
ALTER TABLE Producto ADD CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES CategoriaProducto(id_categoria);
ALTER TABLE Pedido ADD CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente);
ALTER TABLE Pedido ADD CONSTRAINT fk_pedido_estado FOREIGN KEY (id_estado_pedido) REFERENCES EstadoPedido(id_estado_pedido);
ALTER TABLE Pedido ADD CONSTRAINT fk_pedido_metodo_pago FOREIGN KEY (id_metodo_pago) REFERENCES MetodoPago(id_metodo_pago);
ALTER TABLE Pedido ADD CONSTRAINT fk_pedido_tipo_entrega FOREIGN KEY (id_tipo_entrega) REFERENCES TipoEntrega(id_tipo_entrega);
ALTER TABLE Pedido ADD CONSTRAINT fk_pedido_direccion FOREIGN KEY (id_direccion_cliente) REFERENCES DireccionCliente(id_direccion);
ALTER TABLE DetallePedido ADD CONSTRAINT fk_detalle_pedido FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido);
ALTER TABLE DetallePedido ADD CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto) REFERENCES Producto(id_producto);
ALTER TABLE Venta ADD CONSTRAINT fk_venta_pedido FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido);
ALTER TABLE Boleta ADD CONSTRAINT fk_boleta_venta FOREIGN KEY (id_venta) REFERENCES Venta(id_venta);
ALTER TABLE Devolucion ADD CONSTRAINT fk_devolucion_venta FOREIGN KEY (id_venta) REFERENCES Venta(id_venta);

COMMIT;